// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoyKoXgE0QEWo1HwZJ9LnBSd_4MJLf0ok',
    appId: '1:108702759255:web:36a5fed45b80d0c52be612',
    messagingSenderId: '108702759255',
    projectId: 'eapp-7b37a',
    authDomain: 'eapp-7b37a.firebaseapp.com',
    storageBucket: 'eapp-7b37a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaCx3fT5ZuXYWWcLUPaqL_FAsF5LC8UTM',
    appId: '1:108702759255:android:7a3cefb97f1afd052be612',
    messagingSenderId: '108702759255',
    projectId: 'eapp-7b37a',
    storageBucket: 'eapp-7b37a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaQNifI_ar-Iul4QDVNlZ6o43u8UlLcmY',
    appId: '1:108702759255:ios:b08a08b8dd2e38352be612',
    messagingSenderId: '108702759255',
    projectId: 'eapp-7b37a',
    storageBucket: 'eapp-7b37a.appspot.com',
    iosClientId: '108702759255-r3ruh3ur4sqg4rtao4h88ibtnum5km02.apps.googleusercontent.com',
    iosBundleId: 'com.example.eapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaQNifI_ar-Iul4QDVNlZ6o43u8UlLcmY',
    appId: '1:108702759255:ios:b08a08b8dd2e38352be612',
    messagingSenderId: '108702759255',
    projectId: 'eapp-7b37a',
    storageBucket: 'eapp-7b37a.appspot.com',
    iosClientId: '108702759255-r3ruh3ur4sqg4rtao4h88ibtnum5km02.apps.googleusercontent.com',
    iosBundleId: 'com.example.eapp',
  );
}
